# Generated by Django 5.2.7 on 2025-11-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
